### ISSUE TITLE
chore: release checklist

### ISSUE THREAD

**Issue by NickleDave** [vocalpy/vak#733]
Jotting this down, need to formalize later as a template we can cut and paste into "release" issues

- [ ] publish to PyPI
- [ ] look for conda-forge autotick PR
- [ ] make sure CI passes there
- [ ] then make sure build passes when we merge and that binary is actually on conda-forge channel
